// Code generated by "stringer -type Rsa_TE_RESUME_TYPE -linecomment"; DO NOT EDIT.

package rmd4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Rsa_TERT_RESTART-0]
	_ = x[Rsa_TERT_RESUME-1]
	_ = x[Rsa_TERT_QUICK-2]
}

const _Rsa_TE_RESUME_TYPE_name = "重启恢复快速"

var _Rsa_TE_RESUME_TYPE_index = [...]uint8{0, 6, 12, 18}

func (i Rsa_TE_RESUME_TYPE) String() string {
	if i < 0 || i >= Rsa_TE_RESUME_TYPE(len(_Rsa_TE_RESUME_TYPE_index)-1) {
		return "Rsa_TE_RESUME_TYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rsa_TE_RESUME_TYPE_name[_Rsa_TE_RESUME_TYPE_index[i]:_Rsa_TE_RESUME_TYPE_index[i+1]]
}
