// Code generated by "stringer -type=TRsaFtdcBarPrecesType -linecomment"; DO NOT EDIT.

package rmd4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BarPrecesSecond-48]
	_ = x[BarPrecesMinute-49]
	_ = x[BarPrecesDay-50]
}

const _TRsaFtdcBarPrecesType_name = "秒分日"

var _TRsaFtdcBarPrecesType_index = [...]uint8{0, 3, 6, 9}

func (i TRsaFtdcBarPrecesType) String() string {
	i -= 48
	if i >= TRsaFtdcBarPrecesType(len(_TRsaFtdcBarPrecesType_index)-1) {
		return "TRsaFtdcBarPrecesType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TRsaFtdcBarPrecesType_name[_TRsaFtdcBarPrecesType_index[i]:_TRsaFtdcBarPrecesType_index[i+1]]
}
